export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const ALERT_SUCCESS = "ALERT_SUCCESS";
export const ALERT_ERROR = "ALERT_ERROR";
export const ALERT_CLOSE = "ALERT_CLOSE";
export const LOADING = "LOADING";


export const GETALL_REQUEST = 'USERS_GETALL_REQUEST';
export const GETALL_SUCCESS = 'USERS_GETALL_SUCCESS';
export const GETALL_FAILURE = 'USERS_GETALL_FAILURE';


export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';

export const LOGOUT = 'USERS_LOGOUT';


export const DELETE_REQUEST = 'USERS_DELETE_REQUEST';
export const DELETE_SUCCESS = 'USERS_DELETE_SUCCESS';
export const DELETE_FAILURE = 'USERS_DELETE_FAILURE';


export const CREATE_TUTORIAL = "CREATE_TUTORIAL";
export const RETRIEVE_TUTORIALS = "RETRIEVE_TUTORIALS";
export const UPDATE_TUTORIAL = "UPDATE_TUTORIAL";
export const DELETE_TUTORIAL = "DELETE_TUTORIAL";
export const DELETE_ALL_TUTORIALS = "DELETE_ALL_TUTORIALS";


export const CREATE_DEVICE = "CREATE_DEVICE";
export const RETRIEVE_DEVICES = "RETRIEVE_DEVICES";
export const GET_DEVICE = "GET_DEVICE";
export const UPDATE_DEVICE = "UPDATE_DEVICE";
export const DELETE_DEVICE = "DELETE_DEVICE";
export const GET_ALL_DEVICES = "GET_ALL_DEVICES";
export const DELETE_ALL_DEVICES = "DELETE_ALL_DEVICES";




export const CREATE_USER = "CREATE_USER";
export const RETRIEVE_USERS = "RETRIEVE_USERS";
export const GET_USER = "GET_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const DELETE_ALL_USERS = "DELETE_ALL_USERS";


export const GET_ALL_DEVICE_INFO = "GET_ALL_DEVICE_INFO";

export const GET_DEVICE_APP_VERSION = "GET_DEVICE_APP_VERSION";
export const GET_DEVICE_LINUX_VERSION = "GET_DEVICE_LINUX_VERSION";
export const GET_DEVICE_STATUS = "GET_DEVICE_STATUS";
export const GET_DEVICE_UPTIME = "GET_DEVICE_UPTIME";
